config/routes.rb
Traktors::Application.routes.draw do
  resources :orders do
        collection do
          get 'current_orders'
          post 'finish'
        end
    end

  resources :carts do
      collection do
        get 'current_carts'
      end
  end

  resources :images
  devise_for :users
  resources :users

  resources :traktors do
    collection do
      post 'buy'
      get 'search'
      post 'search'
    end
  end

  root :to => 'traktors#index'

end

app/views/shared/_header.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      =link_to "Traktorrr", traktors_path, {:class => "navbar-brand"}
    %ul.nav.navbar-nav.navbar-left
      %li
        =link_to "Тракторы", traktors_path
      %li
        = form_tag({:controller => "/traktors", :action => "search"}, {:class => "navbar-form navbar-left"}) do
          .form-group
            %input.form-control{ name: "name", type:"text", placeholder:"Название трактора"}
          = submit_tag 'Искать', {class: "btn btn-primary", type:"submit"}
      -if current_user.try(:admin?)
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Админ
            %b.caret
          %ul.dropdown-menu
            %li
              =link_to "Тракторы", traktors_path
              =link_to "Юзеры", users_path
              =link_to "Корзины", carts_path
              =link_to "Заказы", orders_path
              =link_to "Изображения", images_path
      -if current_user.try(:moderator?)
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Модератор
            %b.caret
          %ul.dropdown-menu
            %li
              =link_to "Тракторы", traktors_path
              =link_to "Изображения", images_path

    %ul.nav.navbar-nav.navbar-right
      -if user_signed_in?
        -unless @user_carts.blank?
          %li
            = link_to "Моя корзина (#{@user_carts.length})",{controller: :carts, action: :current_carts}
        -unless @user_orders.blank?
          %li
            = link_to "Мои заказы (#{@user_orders.length})",{controller: :orders, action: :current_orders}
        %li
          = link_to "Выйти", destroy_user_session_path
      -else
        %li
          = link_to "Регистрация", new_user_registration_path
        %li
          = link_to "Войти", new_user_session_path