config/routes.rb
Traktors::Application.routes.draw do
  resources :orders do
        collection do
          get 'current_orders'
          post 'finish'
        end
    end

  resources :carts do
      collection do
        get 'current_carts'
      end
  end

  resources :images
  devise_for :users
  resources :users

  resources :traktors do
    collection do
      post 'buy'
      get 'search'
      post 'search'
    end
  end

  root :to => 'traktors#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  belongs_to :traktor
  belongs_to :order

  attr_accessible :traktor_id, :user_id, :order_id, :amount

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :require_admin, :except => [:current_carts, :create, :destroy]

  def current_carts

    @total = 0
    @user_carts.each do |cart|
      @total += cart.traktor.cost
    end
  end

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def calculate_carts
    if user_signed_in?
      @user_carts = current_user.carts.where(:order_id => nil)
    end
  end
end

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :traktor_id
    = f.number_field :traktor_id
  .field
    = f.label :order_id
    = f.number_field :order_id
  .actions
    = f.submit 'Save'

app/views/carts/current_carts.haml
.col-md-10.col-md-offset-1
  %h1 Корзина
  - @user_carts.each do |cart|
    .row.panel.panel-default
      .panel-body
        .col-md-3
          = image_tag cart.traktor.images.first.url, {class: "img-thumbnail"}
        .col-md-9
          %h2= cart.traktor.name
          %p= cart.traktor.description
          .pull-right.text-right
            = link_to 'Отказаться', cart, :method => :delete, class: "btn btn-danger", :data => { :confirm => 'Вы уверены?' }
            %h4
              Цена:
              %strong
                = cart.traktor.cost
                р.
  .row.panel.panel-default
    .panel-body
      %h3.pull-right
        Итого:
        %strong
          = @total
          р.
  =link_to 'Оформить заказ', new_order_path, {:class => "btn btn-primary pull-right"}

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table.table.table-striped.table-hover
  %tr
    %th User
    %th Traktor
    %th Order
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= cart.user_id
      %td= cart.traktor_id
      %td= cart.order_id
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
%p#notice= notice

%p
  %b User:
  = @cart.user_id
%p
  %b Traktor:
  = @cart.traktor_id

= link_to 'Edit', edit_cart_path(@cart)
\|
= link_to 'Back', carts_path