config/routes.rb
Traktors::Application.routes.draw do
  resources :orders do
        collection do
          get 'current_orders'
          post 'finish'
        end
    end

  resources :carts do
      collection do
        get 'current_carts'
      end
  end

  resources :images
  devise_for :users
  resources :users

  resources :traktors do
    collection do
      post 'buy'
      get 'search'
      post 'search'
    end
  end

  root :to => 'traktors#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :traktor_id, :url

  belongs_to :traktor
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_filter :require_admin

  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :traktor_id
    = f.number_field :traktor_id
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table.table.table-striped.table-hover
  %tr
    %th Traktor
    %th Url
    %th img
    %th
    %th
    %th

  - @images.each do |image|
    %tr
      %td= image.traktor_id
      %td= image.url
      %td= image_tag image.url, {class: "img-thumbnail"}
      %td= link_to 'Show', image
      %td= link_to 'Edit', edit_image_path(image)
      %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b Traktor:
  = @image.traktor_id
%p
  %b Url:
  = @image.url

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path